apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: aihub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi