apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcjob
  namespace: aihub
  labels:
    name: pvcjob
spec:
  accessModes:
  - ReadWriteMany
  #volumeMode: Filesystem
  #storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv