apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvctask
  namespace: aihub
  labels:
    name: pvctask
spec:
  accessModes:
  - ReadWriteMany
  #volumeMode: Filesystem
  #storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv