apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: aihub
  labels:
    name: pv
spec:
  nfs:
    path: /data/nfs
    server: 192.168.196.130
  volumeMode: Filesystem
  #storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain