apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: aihub
  labels:
    name: pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  #storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv