apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: aihub
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: pv
      mountPath: /pvc
      readOnly: false
    ports:
    - containerPort: 80
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: pvc